### ISSUE TITLE
last of array is empty

### ISSUE THREAD

**Issue by cacard** [f3ath/jessie#1]
on windows and mac
dart version:2.10.0
using the example code : https://pub.dev/packages/json_path/example

json path is : $['store']['book'][3]['price']
return empty.

**Comment by f3ath** [comment]
@cacard thank you for reporting the issue. Sorry it took me long to notice it. It should be fixed in [0.0.2](https://pub.dev/packages/json_path/versions/0.0.2). Please confirm.
