### ISSUE TITLE
Select object from list where key inside an object contains dynamic value

### ISSUE THREAD

**Issue by AlcoholicCoder** [f3ath/jessie#103]
In Javascript I did this to find value where `key` ends with `BAR`: `$.values[?(@.key.endsWith('BAR'))].value`
Works on: [https://jsonpath.com](https://jsonpath.com)

```
{
  "values": [
    { "key": "1199-FOO", "value": 1199 },
    { "key": "8877-BAR", "value": 8877 }
  ]
}
```

How can I achieve this in DART?
`json_path` keeps throwing `ParserException` for `$.values[?(@.key =~ /.*BAR/)].value`

**Comment by f3ath** [comment]
You can use the [match()](https://www.rfc-editor.org/rfc/rfc9535.html#name-match-function-extension) function: `$.values[?match(@.key, '.*BAR')]`.

**Comment by AlcoholicCoder** [comment]
> You can use the [match()](https://www.rfc-editor.org/rfc/rfc9535.html#name-match-function-extension) function: `$.values[?match(@.key, '.*BAR')].value`.

Thank you for your quick reply. Is there any similar function for key names as well?
```
{
    "ynid": "AX0086HHN",
    "Serial Group": "009722918001826A"
}
```
For example I want to get result `009722918001826A` but key name might be `Serial Group/Serial Name/Serial Number/Serial XYZ`. Only `Serial` is static and will be always there.

**Comment by f3ath** [comment]
Starting from the latest version 0.7.2, this package comes with the non-standard function `key()` which you may use like this `$[?match(key(@), 'Serial .*')]`. Given the following document
```json
{
        "ynid": "AX0086HHN",
        "Serial Group": "009722918001826A",
        "Serial Name": "foo",
        "Serial Number": "bar",
        "serial whatever": "baz"
      }
```
the matched values will be:
- `"009722918001826A"`
- `"foo"`
- `"bar"`

Note that `"baz"` will not be matched since `match()` is case-sensitive. You can craft your own custom functions and supply them to the parser, see the [example](https://github.com/f3ath/jessie/blob/master/example/custom_functions.dart):

```dart
import 'dart:convert';

import 'package:json_path/fun_sdk.dart';
import 'package:json_path/json_path.dart';

/// This example shows how to create and use a custom function.
void main() {
  final parser = JsonPathParser(functions: [IsPalindrome()]);
  final jsonPath = parser.parse(r'$[?is_palindrome(@)]');
  final json = jsonDecode('["madam", "foo", "nurses run", 42, {"A": "B"}]');
  jsonPath.readValues(json).forEach(print);
}

/// An implementation of a palindrome test.
class IsPalindrome implements Fun1<bool, Maybe> {
  @override
  final name = 'is_palindrome';

  @override
  bool call(Maybe arg) => arg
      .type<String>() // Make sure it's a string
      .map((value) => value.replaceAll(' ', '')) // drop spaces
      .map((value) => value.split('').reversed.join() == value) // palindrome?
      .or(false); // for non-string values return false
}
```

**Comment by AlcoholicCoder** [comment]
Thank you. God bless you!
