### ISSUE TITLE
json path not find the array length

### ISSUE THREAD

**Issue by varindergroove** [f3ath/jessie#114]
I try to find the json array length using the expression $.data.length 

json = {
  "data": [
    {
      "auto_id": 5
    },
    {
      "auto_id": 6
    }
  ]
}

I try to find online json path finder its working fine this expression 
https://jsonpath.com/

Please resolve this or provide another solution

**Comment by f3ath** [comment]
I think you're looking for the [length()](https://datatracker.ietf.org/doc/html/rfc9535#section-2.4.4) function.
```
length($.data)
```

**Comment by varindergroove** [comment]
this is very tricky solution,  you are not follow the json path expression 
according to json expression $.data.length

please follow this website and test this
https://jsonpath.com/

I have not implement this expression 
length($.data)

and also explain with example to use like this.

**Comment by f3ath** [comment]
The JSONPath query language is described by RFC 9535, which is the standard used by this Dart package. The RFC 9535 says nothing about the `.length` property that you're referring to. Whatever the implementation is in jsonpath.com, it doesn't seem to follow the standard.

**Comment by f3ath** [comment]
As for the examples, you may find a few examples in the JSONPath Compliance Test Suite https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/blob/main/tests/functions/length.json
