### ISSUE TITLE
Filtering doesn't work?

### ISSUE THREAD

**Issue by wstrange** [f3ath/jessie#2]
I'm trying to use a filter:

```
 JsonPath(r'$.metadata.realm', filter: {
      'realm': (e) {
        _log.finer('filtered $e');
        return true;
      }
    })
```

I find that the filter test never gets invoked, even thought the json contains a realm expression:

```
FINER: 2020-08-25 18:39:38.536755: $['metadata']['realm']:	/
```

Maybe a doc issue?

**Comment by f3ath** [comment]
@wstrange Can you try this one please:
```dart
 JsonPath(r'$.metadata[?realm]', filter: {
      'realm': (e) {
        _log.finer('filtered $e');
        return true;
      }
    })
```


If it doesn't work, would you please provide a test dataset to reproduce the issue?

**Comment by wstrange** [comment]
That worked - thanks!
