### ISSUE TITLE
Adapting json_path

### ISSUE THREAD

**Issue by Dokotela** [f3ath/jessie#23]
Hello! Thanks so much for this package. I'm somewhat new to path-based navigation, so I was hoping I could ask for some help. I work with a data format called FHIR (https://www.hl7.org/fhir/overview.html). It's all json based. There is another specification called FHIRPath (http://hl7.org/fhirpath/), which is a path based navigation and extraction language. It is similar to XPath, and it certainly appears similar to JSONPath. However, it does have some idiosyncracies. Do you think I could implement these requirements using this package, or do you think I need to use petitparser and build it from the ground up?

**Comment by f3ath** [comment]
Hi. As far as I see, the FHIRPath is not fully compatible with JSONPath and it also supports an extensive set of functions and expressions which are not included in JSONPath [implementations](https://cburgmer.github.io/json-path-comparison/). I'm fine with extending the library as long as it does not break existing features (i.e. all tests still pass) but it does not seem to be an easy task. So you will need to implement your own grammar to say the least. It would be super cool if this library was flexible enough to support different query dialects (grammars) while maintaining the same external API, but that's a challenge if its own. Most likely FHIR dialect implementation will diverge too much, but I'd be glad to be proven wrong :) Feel free to (re)use any part of this code for FHIR implementation as well as contribute back to this repo.

**Comment by Dokotela** [comment]
Hey, thanks for the fast reply! That's fair. I'll play around with it for a while to see if I can just extend it. But as you say, that may not be possible without breaking some things. Either way, I appreciate the input, and if I end up making anything that I feel is useful, I'll be sure to give you a pull request!

**Comment by f3ath** [comment]
Closing this.Feel free to reopen.
