### ISSUE TITLE
how to concat variable in json path

### ISSUE THREAD

**Issue by abigoroth** [f3ath/jessie#24]
I tried with this but no success
``` "\$.wallets[$widget.walletsIndex]['balance']" ```

**Comment by f3ath** [comment]
Hi. Not sure what you are trying to achieve, but complex expressions, including concatenation, back reference, etc., are not supported. You may want to try callbacks: https://github.com/f3ath/jessie#features-and-limitations

**Comment by abigoroth** [comment]
> Hi. Not sure what you are trying to achieve, but complex expressions, including concatenation, back reference, etc., are not supported. You may want to try callbacks: https://github.com/f3ath/jessie#features-and-limitations

I split it with like this `"\$.wallets["+widget.walletsIndex+"]['balance']"` .Thankfully it works.

**Comment by f3ath** [comment]
I think what you were looking for was `"\$.wallets[${widget.walletsIndex}]['balance']"`
