### ISSUE TITLE
end of input expected at 1:2 for Expression: $.[*].value

### ISSUE THREAD

**Issue by SahajRana** [f3ath/jessie#28]
Hi @f3ath, thanks for the library.

I'm receiving this error,
```
end of input expected at 1:2. Expression: $.[*].value

The relevant error-causing widget was: 
 ...
When the exception was thrown, this was the stack: 
#0      JsonPath._parse (package:json_path/src/json_path.dart:41:7)
#1      new JsonPath (package:json_path/src/json_path.dart:35:21)
```

Code:
```
final json = jsonDecode('''
[{"value": "HELLEBORUS BERBERIS SPECIAL ORDER"}, {"value": "HELLEBORUS COMP. A"}, {"value": "HELLEBORUS COMP. B"}, {"value": "HELLEBORUS COMP. C"}, {"value": "HELLEBORUS COMP. D"}]
  ''');

    final prices = JsonPath(r'$.[*].value');
    var val=prices.read(json);
    for (var element in val) {
      print("value>> "+element.value.toString());
      print("path>> "+element.path.toString());
      print("pointer>> "+element.pointer.toString());
    }
```

But this works here in the online evaluator for json path
https://jsonpath.com/

I believe there is a case that have been missed during pepitparser expression creation in this library.

**Comment by f3ath** [comment]
Hi @SahajRana Expression `$.[*].value` does not seem to be a properly formed JsonPath expression. Specifically, this part: `$.[*]`. While there is no well-defined standard of JsonPath yet, there is some work being done towards it:
- https://cburgmer.github.io/json-path-comparison/
- https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base

None of those documents (neither the reference implementation by Stefan Goessner) mentions this expression. I believe it is malformed, so this library does not support it.

What you probably want is either `$[*].value` or `$.*.value`, both should work and produce the result you expect.

**Comment by SahajRana** [comment]
Thanks for clarifying the confusion.
