### ISSUE TITLE
RFE: Set a value

### ISSUE THREAD

**Issue by wstrange** [f3ath/jessie#3]
If you are looking for suggestions to enhance this library, this would be a neat feature:

https://github.com/json-path/JsonPath#set-a-value

**Comment by f3ath** [comment]
Check out the [new version](https://pub.dev/packages/json_path/versions/0.1.0) :)

**Comment by neuos** [comment]
Setting a value at an existing path works great, but it would also be a great feature to set a value to a path that does not yet exist.

```
test('write to non existing path', () {
    var myJSON = {'name': 'neuos'};
    var path = r'$.a.b';
    var value = 'world';
    myJSON = JsonPath(path).set(myJSON, value);

    var expected = {'name':'neuos', 'a':{'b':'world'}};
    expect(myJSON, expected);
  });
```

In this example the original unmodified myJson gets returned. It would be great if the path would be created to set the value.

**Comment by neuos** [comment]
Setting a value at an existing path works great, but it would also be a great feature to set a value to a path that does not yet exist.

```
test('write to non existing path', () {
    var myJSON = {'name': 'neuos'};
    var path = r'$.a.b';
    var value = 'world';
    myJSON = JsonPath(path).set(myJSON, value);

    var expected = {'name':'neuos', 'a':{'b':'world'}};
    expect(myJSON, expected);
  });
```

In this example the original unmodified myJson gets returned. It would be great if the path would be created to set the value.

**Comment by f3ath** [comment]
@neuos how about now?

**Comment by neuos** [comment]
Great, it works for simple paths now. But is still have a problem where I can't set to a non existing array. For example if i have an empty JSON and want to set a value to a path that contains an array it just stops at the array and sets that to null.
```
test('write to path with non existing array', () {
    final json = {};
    var path = r'$.a.arr[0].b.foo';
    var value = 'bar';
    final mutated = JsonPath(path).set(json, value);

    final expected = {
      'a':{'arr': [{'b':{'foo':'bar'}}]}
    };
    
    // Actual: {'a': {'arr': null}}
    expect(mutated, expected);
  });
```

**Comment by f3ath** [comment]
@neuos this case should work [now](https://pub.dev/packages/json_path/versions/0.2.0).

**Comment by neuos** [comment]
Great it works now as expected

**Comment by neuos** [comment]
With the removal of the set method in 0.3.0 I can't figure out how to set a value to a path that does not yet exist, because there is no match I can get the pointer from.

**Comment by f3ath** [comment]
@neuos version 0.3.0 comes with a [JsonPointer](https://pub.dev/packages/rfc_6901) implementation which, unlike JsonPath, is a [standard](https://tools.ietf.org/html/rfc6901). For non-existent values, please use JsonPointer. Here's an [example](https://pub.dev/packages/rfc_6901/example) and [tests](https://github.com/f3ath/rfc-6901-dart/blob/main/test/writing_test.dart). Please let me know if it works for you.

**Comment by neuos** [comment]
@f3ath It works for simple cases but the case to set at a non eexisting array fails silently.

works in 0.2.0:

```
test('write to path with non existing array', () {
    final json = {};
    var path = r'$.a.arr[0].b.foo';
    var value = 'bar';
    final mutated = JsonPath(path).set(json, value);

    final expected = {
      'a':{'arr': [{'b':{'foo':'bar'}}]}
    };
    
    // Actual: {'a': {'arr': null}}
    expect(mutated, expected);
  });test('write to path with non existing array', () {
    final json = {};
    var path = r'$.a.arr[0].b.foo';
    var value = 'bar';
    final mutated = JsonPath(path).set(json, value);

    final expected = {
      'a':{'arr': [{'b':{'foo':'bar'}}]}
    };
    
    // Actual: {'a': {'arr': null}}
    expect(mutated, expected);
  });
```

doesn't work in rfc_6901 0.1.0: 
```
test('write to path with non existing array using rfc_6901', () {
      final json = {};
      final pointer = JsonPointer('/a/arr/-/b/foo');
      final value = 'bar';

      final mutated = pointer.write(json, value);

      final expected = {
        'a': {
          'arr': [
            {
              'b': {'foo': value}
            }
          ]
        }
      };

      expect(mutated, expected);
      expect(jsonRead(json, '/a/arr/0/b/foo'), null);
      expect(jsonRead(mutated, '/a/arr/0/b/foo'), value);
    });
```

**Comment by neuos** [comment]
Thanks. Sorry for the late answer. It took some extra effort to be able to write at arrays that don't exist yet, but now it all works.
