### ISSUE TITLE
Running "flutter pub get" problem 

### ISSUE THREAD

**Issue by Abdullatif-Eida** [f3ath/jessie#31]
To Reproduce (i.e. user steps, not code)

Go to ' terminal make flutter upgrade be sure the Version is 2.10.4  on channel stable'
Click on 'run flutter pub get'
See error
Error messages

What went wrong:
Because every version of flutter_test from sdk depends on collection 1.15.0 and xml >=5.4.0 depends on collection ^1.16.0, flutter_test from sdk is incompatible with xml >=5.4.0.
And because flutter_native_splash >=1.3.0 depends on xml ^5.3.1, if flutter_test from sdk and flutter_native_splash >=1.3.0 then xml >=5.3.1 <5.4.0.
And because xml >=5.3.0 <5.4.0 depends on petitparser ^4.3.0 and json_path 0.4.0 depends on petitparser ^5.0.0, one of flutter_test from sdk or flutter_native_splash >=1.3.0 or json_path 0.4.0 must be false.
And because no versions of json_path match >0.4.0 <0.5.0 and flutter_project depends on json_path ^0.4.0, flutter_test from sdk is incompatible with flutter_native_splash >=1.3.0.
So, because flutter_project depends on both flutter_native_splash ^2.0.4 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because flutter_project depends on both flutter_native_splash ^2.0.4 and flutter_test from sdk, version solving failed.)

Expected behavior
i am Expecting my app to run without any problem

Screenshots

Desktop (please complete the following information):

OS: [e.g. MacOS Big Sur + 11.6.2]
Browser [e.g. chrome + 99.0.4844.82]
Smartphone (please complete the following information):

Device: [e.g. Pixel 3 a]
OS: [e.g. Android Tiramisu]
Flutter SDK version
environment:
sdk: ">=2.16.1 <3.0.0"

Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

insert output of "flutter doctor -v" here
[✓] Flutter (Channel stable, 2.10.4, on macOS 11.6.2 20G314 darwin-x64, locale en-TR)
    • Flutter version 2.10.4 at /Users/imac/flutterDevelopment/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (7 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (4 available)
    • SM A125F (mobile)      • R58R21ZSWAR                          • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 4326275E-EB0C-4C06-A7B2-B30861DE3A38 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.6.2 20G314 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.60
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

Additional context
I am trying to use json_path on last version of flutter 
Because every version of flutter_test from sdk depends on collection 1.15.0 and xml >=5.4.0 depends on collection ^1.16.0, flutter_test from sdk is incompatible with xml >=5.4.0.
And because flutter_native_splash >=1.3.0 depends on xml ^5.3.1, if flutter_test from sdk and flutter_native_splash >=1.3.0 then xml >=5.3.1 <5.4.0.
And because xml >=5.3.0 <5.4.0 depends on petitparser ^4.3.0 and json_path 0.4.0 depends on petitparser ^5.0.0, one of flutter_test from sdk or flutter_native_splash >=1.3.0 or json_path 0.4.0 must be false.
And because no versions of json_path match >0.4.0 <0.5.0 and flutter_project depends on json_path ^0.4.0, flutter_test from sdk is incompatible with flutter_native_splash >=1.3.0.
So, because flutter_project depends on both flutter_native_splash ^2.0.4 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because flutter_project depends on both flutter_native_splash ^2.0.4 and flutter_test from sdk, version solving failed.)

is there any solution

Note: when deleting one of json_path from pubspec.yaml the app run without any problem

**Comment by f3ath** [comment]
Hi. Seems to be a version resolution issue. Have you tried downgrading to json_path 0.3?

**Comment by f3ath** [comment]
Closing for now. Feel free to reopen.
