### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by hicnar** [f3ath/jessie#39]
And here's the message:

Launching lib/main_basic.dart on iPhone 13 in debug mode...
Running Xcode build...
Xcode build done.                                           26.5s
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/json_path-0.4.3/lib/src/grammar/expression.dart:40:7: Error: The method 'primitive' isn't defined for the class 'ExpressionBuilder<dynamic Function(JsonPathMatch)>'.

Could not build the application for the simulator.
Error launching application on iPhone 13.

**Comment by f3ath** [comment]
Oh, I guess I will need to bump the minimal version of petitparser. Meanwhile, can you please try running dart pub upgrade?

**Comment by f3ath** [comment]
Please update to 0.4.4.

**Comment by hicnar** [comment]
Will do as soon as I get home 🙃

**Comment by f3ath** [comment]
Should be fixed now. Feel free to reopen.

**Comment by hicnar** [comment]
0.4.4 fixed the bug.
Cheers
