### ISSUE TITLE
Please unpublish 0.4.3 and republish as 0.5.0

### ISSUE THREAD

**Issue by jpeiffer** [f3ath/jessie#40]
json_path 0.4.3 suggest it's a non-breaking upgrade from 0.4.2, but that's not actually the case.  The version 0.4.2 worked with petitparser 5.1.0, but 0.4.3 requires 5.2.0+.

That's a problem because petitparser 5.1.0 depends on meta 1.8.0 (the one currently in Flutter stable), but 5.2.0+ depends on meta 1.9.0.  This makes petitparser 5.2.0+ unable to be used in any application on Flutter stable, which also makes 0.4.2 Flutter  compatible and 0.4.3 as non-Flutter compatible.

Ideally when there's a breaking change that should be noted in the semver so users aren't automatically upgraded to a broken state.

I tried contacting the author of petitparser about the issue via: https://github.com/petitparser/dart-petitparser/issues/144

Someone else tried contacting the Flutter folks about this same issue: https://github.com/flutter/flutter/issues/121391

They both collectively gave a `¯\_(ツ)_/¯`.  I'm hoping for a more helpful / positive outcome here.

**Comment by f3ath** [comment]
Reverted the changes in 0.4.4. Please try updating.

**Comment by f3ath** [comment]
Should be fixed now. Feel free to reopen.

**Comment by jpeiffer** [comment]
Thanks!
