### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by dzakyraf** [f3ath/jessie#64]
Thankyou for wonderful plugin, but i occured problem when build in flutter 3.7.10.  The error say like this :

```
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../../../.pub-cache/hosted/pub.dev/json_path-0.5.3/lib/src/grammar/strings.dart:43:51:
Error: The method 'timesString' isn't defined for the class 'Parser<String>'.
 - 'Parser' is from 'package:petitparser/src/core/parser.dart' ('../../../.pub-cache/hosted/pub.dev/petitparser-5.1.0/lib/src/core/parser.dart').
final _unicodeSymbol = (string(r'\u') & _hexDigit.timesString(4))
```

**Comment by Matthiee** [comment]
Same issue here it got broken in https://github.com/f3ath/jessie/commit/340bd5c3bbaab81379e3a0aa63ee7a274a7d44aa

I reverted back to using 0.5.2 that version seems to work fine for now.

**Comment by f3ath** [comment]
Most likely the reason is a particular petitparser version. I revoked 0.5.3 for now.
